### ISSUE TITLE
"are you binding to the correct local IP?"

### ISSUE THREAD

**Issue by pannous** [ymartineau/peers#34]
do we have to start a local server?

getting "are you binding to the correct local IP?"

```

2018-06-11 12:26:32,313 DEBUG [Transaction timer] SM z9hG4bKDerhnghSS|INVITE [InviteClientTransactionStateCalling -> InviteClientTransactionStateCalling] setState
2018-06-11 12:26:32,313 DEBUG [Transaction timer] UdpMessageSender.sendMessage
2018-06-11 12:26:32,314 ERROR [Transaction timer] are you binding to the correct local IP? (local IP, not the routers IP)
2018-06-11 12:26:32,314 ERROR [Transaction timer] throwable
java.lang.Exception: java.io.IOException: Invalid argument (sendto failed)
	at com.pannous.call.sip.transport.UdpMessageSender.sendBytes(UdpMessageSender.java:70)
	at com.pannous.call.sip.transport.UdpMessageSender.sendMessage(UdpMessageSender.java:52)
	at com.pannous.call.sip.transaction.InviteClientTransaction.sendRetrans(InviteClientTransaction.java:205)
	at com.pannous.call.sip.transaction.InviteClientTransactionStateCalling.timerAFires(InviteClientTransactionStateCalling.java:36)
	at com.pannous.call.sip.transaction.InviteClientTransaction$TimerA.run(InviteClientTransaction.java:226)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
```

**Comment by ymartineau** [comment]
no, peers opens a udp socket on a specific ip address and your pc might
have several ip addresses, so you should use the right one so that peers
starts successfully.
By the way, i didn't use that kind of error message in peers, so I don't
know where your code is coming from but probably need directly from the
ymartineau/peers github repository.

yohann

2018-06-11 13:28 GMT+02:00 pannous <notifications@github.com>:

**Comment by pannous** [comment]
thanks for your support!!
Yeah that was a fork but original peers shows same error:
```
REGISTER sip:fpbx.de SIP/2.0
Via: SIP/2.0/UDP 127.0.0.1:54429;rport;branch=z9hG4bKtnGOuOo97
Max-Forwards: 70
To: <sip:777010041698@fpbx.de>
From: <sip:777010041698@fpbx.de>;tag=xToLGRDH
Call-ID: 4E0d4zjq-1528792558078@localhost
CSeq: 3 REGISTER
Expires: 3600
Contact: <sip:777010041698@127.0.0.1:54429;transport=UDP>


2018-06-12 09:36:21,622 DEBUG [TransactionManager Timer] SM z9hG4bKtnGOuOo97|REGISTER [NonInviteClientTransactionStateTrying -> NonInviteClientTransactionStateTrying] setState
2018-06-12 09:36:21,622 DEBUG [TransactionManager Timer] UdpMessageSender.sendMessage
2018-06-12 09:36:21,623 DEBUG [TransactionManager Timer] UdpMessageSender.sendBytes
2018-06-12 09:36:21,623 DEBUG [TransactionManager Timer] UdpMessageSender.sendBytes 328 fpbx.de/185.79.24.137:5060
2018-06-12 09:36:21,623 DEBUG [TransactionManager Timer] /127.0.0.1
2018-06-12 09:36:21,623 ERROR [TransactionManager Timer] throwable
java.lang.Exception: java.io.IOException: Invalid argument (sendto failed)
	at net.sourceforge.peers.sip.transport.UdpMessageSender$1.run(UdpMessageSender.java:78)
	at net.sourceforge.peers.sip.transport.UdpMessageSender$1.run(UdpMessageSender.java:70)
	at java.security.AccessController.doPrivileged(Native Method)
	at net.sourceforge.peers.sip.transport.UdpMessageSender.sendBytes(UdpMessageSender.java:69)
	at net.sourceforge.peers.sip.transport.UdpMessageSender.sendMessage(UdpMessageSender.java:54)
	at net.sourceforge.peers.sip.transaction.NonInviteClientTransaction.sendRetrans(NonInviteClientTransaction.java:138)
	at net.sourceforge.peers.sip.transaction.NonInviteClientTransactionStateTrying.timerEFires(NonInviteClientTransactionStateTrying.java:41)
	at net.sourceforge.peers.sip.transaction.NonInviteClientTransaction$TimerE.run(NonInviteClientTransaction.java:178)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
Caused by: java.io.IOException: Invalid argument (sendto failed)
	at java.net.PlainDatagramSocketImpl.send(Native Method)
	at java.net.DatagramSocket.send(DatagramSocket.java:693)
	at net.sourceforge.peers.sip.transport.UdpMessageSender$1.run(UdpMessageSender.java:76)
	... 9 more
2018-06-12 09:36:21,624 DEBUG [TransactionManager Timer] UdpMessageSender.sendBytes packet sent
2018-06-12 09:36:21,624 SENT to 185.79.24.137/5060 [TransactionManager Timer]
```

And sorry for asking: where can IP address be chosen? should only be one anyways.
Same settings work with yate client.

I tried with stun server as proxy too.

**Comment by pannous** [comment]
yay, it works by manually copying IP from ifconfig to peers.xml

if you want I will create a pull request which will automatically do that

**Comment by pannous** [comment]
FYI I'm using your great lib to recreate google duplex:
https://www.youtube.com/watch?v=bd1mEm2Fy08

We did the same 5 years ago and will reactivate it: 
https://www.fiverr.com/pannous/make-phone-calls-on-your-behalf
